"""Add referal_amount column

Revision ID: 4f5945fb18ee
Revises: 656af3db229d
Create Date: 2025-06-16 21:25:38.187106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5945fb18ee'
down_revision: Union[str, None] = '656af3db229d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('referal_amount', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('time_register', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'time_register')
    op.drop_column('Users', 'referal_amount')
    # ### end Alembic commands ###
