"""create Gifts  table

Revision ID: c28705410e2f
Revises: 2cca081d89f4
Create Date: 2025-06-15 14:43:30.805015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28705410e2f'
down_revision: Union[str, None] = '2cca081d89f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gifts', sa.Column('rarity', sa.String(), nullable=False))
    op.add_column('Gifts', sa.Column('owned_id', sa.String(), nullable=False))
    op.drop_column('Gifts', 'play_win')
    op.drop_column('Gifts', 'referals')
    op.drop_column('Gifts', 'referer')
    op.drop_column('Gifts', 'balance_star')
    op.drop_column('Gifts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gifts', sa.Column('user_id', sa.BIGINT(), nullable=False))
    op.add_column('Gifts', sa.Column('balance_star', sa.BIGINT(), nullable=False))
    op.add_column('Gifts', sa.Column('referer', sa.BIGINT(), nullable=False))
    op.add_column('Gifts', sa.Column('referals', sa.INTEGER(), nullable=False))
    op.add_column('Gifts', sa.Column('play_win', sa.INTEGER(), nullable=False))
    op.drop_column('Gifts', 'owned_id')
    op.drop_column('Gifts', 'rarity')
    # ### end Alembic commands ###
